var gen = {};

// npcs
gen.npc = {};
gen.npc.race = [
  `Human`,
  `Elf`,
  `Dwarf`,
  `Tiefling`,
  `Aasimar`,
  `Half-Elf`,
  `Eldarin`,
  `Gith`,
  `Goblin`,
  `Dragonborn`,
  `Gnome`,
  `Half-Orc`,
  `Halfling`,
  `Drow`,
  `Genasi`,
  `Goliath`,
  `Kobold`,
  `Gnoll`,
  `Illithid`,
  `Orc`,
  `Warforged`,
  `Weren`,
  `Koa-toa`,
  `Aarakocra`,
];
gen.npc.appearance = [
  `Distinctive jewelry: earrings, necklace, circlet, bracelets`,
  `Piercings`,
  `Flamboyant or outlandish clothes`,
  `Formal, clean clothes`,
  `Ragged, dirty clothes`,
  `Pronounced scar`,
  `Missing teeth`,
  `Missing fingers`,
  `Unusual eye color (or two different eye colors)`,
  `Tattoos`,
  `Birthmark`,
  `Unusual skin color`,
  `Bald`,
  `Braided beard or hair`,
  `Unusual hair color`,
  `Nervous eye twitch`,
  `Distinctive nose`,
  `Distinctive posture (crooked or rigid)`,
  `Exceptionally beautiful`,
  `Exceptionally ugly`,
];
gen.npc.talent = [
  `Plays a musical instrument`,
  `Speaks several languages fluently`,
  `Unbelievably lucky`,
  `Perfect memory`,
  `Great with animals`,
  `Great with children`,
  `Great at solving puzzles`,
  `Great at one game`,
  `Great at impersonation`,
  `Draws beautifully`,
  `Paints beautifully`,
  `Sings beautifully`,
  `Drinks everyone under the table`,
  `Expert carpenter`,
  `Expert cook`,
  `Expert dark thrower and rock skipper`,
];
gen.npc.mannerism = [
  `Prone to singing, whistling, or humming quietly`,
  `Speaks in rhyme or some other peculiar way`,
  `Particularly low or high voice`,
  `Slurs words, lisps, or stutters`,
  `Enunciates overly clearly`,
  `Speaks loudly`,
  `Whispers`,
  `Uses flowery speech or long words`,
  `Frequently uses the wrong word`,
  `Uses colorful oaths and exclaimations`,
  `Makes constant jokes or puns`,
  `Prone to predictions of doom`,
  `Fidgets`,
  `Squints`,
  `Stares into the distance`,
  `Chews something`,
  `Paces`,
  `Taps fingers`,
  `Bites fingernails`,
  `Twirls hair or tugs beard`,
];
gen.npc.personality = [
  `Argumentative`,
  `Arrogant`,
  `Blustering`,
  `Rude`,
  `Curious`,
  `Friendly`,
  `Honest`,
  `Hot tempered`,
  `Irritable`,
  `Ponderous`,
  `Suspicious`,
];
gen.npc.ideal = [
  `Beauty`,
  `Charity`,
  `Greater Good`,
  `Life`,
  `Respect`,
  `Self-sacrifice`,
  `Community`,
  `Fairness`,
  `Honor`,
  `Logic`,
  `Responsibility`,
  `Tradition`,
  `Balance`,
  `Knowledge`,
  `Live and let live`,
  `Moderation`,
  `Neutrality`,
  `People`,
  `Domination`,
  `Greed`,
  `Might`,
  `Pain`,
  `Retribution`,
  `Slaughter`,
  `Change`,
  `Creativity`,
  `Freedom`,
  `Independence`,
  `No limits`,
  `Whimsy`,
  `Aspiration`,
  `Discovery`,
  `Glory`,
  `Nation`,
  `Redemption`,
  `Self-knowledge`,
];
gen.npc.bond = [
  `Dedicated to fulfilling a personal life goal`,
  `Protective of close family members`,
  `Protective of colleagues or compatriots`,
  `Loyal to a benefactor, patron, or employer`,
  `Captivated by a romantic interest`,
  `Drawn to a special place`,
  `Protective of a sentimental keepsake`,
  `Protective of a valuable possession`,
  `Out for revenge`,
];
gen.npc.flaw = [
  `Forbidden love or susceptibility to romance`,
  `Enjoys decadent pleasures`,
  `Arrogance`,
  `Envies another creature's possessions or station`,
  `Overpowering greed`,
  `Prone to rage`,
  `Has a powerful enemy`,
  `Specific phobia`,
  `Shameful or scandalous history`,
  `Secret crime or misdeed`,
  `Possession of forbidden lore`,
  `Foolhardy bravery`,
];
// magic items
gen.item = {};
gen.item.type = [
  `sword`,
  `not sword`,
]
gen.item.origin = [
  `Abberation`,
  `Human`,
  `Celestial`,
  `Dragon`,
  `Drow`,
  `Dwarf`,
  `Elemental Air`,
  `Elemental Fire`,
  `Elemental Water`,
  `Elemental Earth`,
  `Gith`,
  `Sigil Guild`,
  `Primitive World`,
  `Technological World`,
  `Illithid`,
  `Elven`,
  `Fey`,
  `Fiendish`,
  `Giant`,
  `Gnomish`,
  `Undead`,
  `Aasimar`,
];
gen.item.history = [
  `Built for an order of mages`,
  `Bane of a race of creatures`,
  `Once wielded by a great hero`,
  `Made to honor a special occasion`,
  `Featured in a prophecy`,
  `Religious significance`,
  `History of sinister wielders`,
  `Symbol of power`,
];
gen.item.property = [
  `Sheds light at will (20/10ft bright/dim)`,
  `Usable as a compass`,
  `Enhances goodness of wielder`,
  `Wielder is never lost underground`,
  `Item never gets dirty`,
  `Wielder is more alert (+2 initiative)`,
  `Item hides a hidden message`,
  `Item is a key to something`,
  `Wielder doesn't need to eat or breathe`,
  `Wielder doesn't age`,
  `Wielder speaks a new language`,
  `Item glows in presense of certain creatures`,
  `Sings when struck`,
  `Made of unusual materials`,
  `Wielder resists extreme temperatures`,
  `Unbreakable`,
  `Wielder has a booming voice`,
  `Item floats on water`,
  `Enhances wickedness of wielder`,
  `Item is partly illusion and customizable`,
  ];
gen.item.quirk = [
  `Wielder feels fortunate and is followed by butterflies`,
  `Imbues wielder with confidence`,
  `Bearer becomes obsessed with wealth`,
  `Item is chipped, crumbling, or cracked and looks ready to fall apart`,
  `Item only functions with a drop of fresh blood`,
  `Makes loud noise when used`,
  `Changes appearance slightly perodically`,
  `Grumbles and mutters, once in a while says something useful`,
  `Bearer feels flashes of pain with use`,
  `Possessive, drug-like and addictive when used`,
  `Repulsive, nauseating and uncomfortable to use`,
  `Bearer feels slothful, requires extra rest`,
];
// magic item tables
gen.item.table = {}
gen.item.table.a = [
  "Potion of Healing",
  "Spell scroll (cantrip)",
  "Potion of Climbing",
  "Spell scroll (1st level)",
  "Spell scroll (2nd level)",
  "Potion of greater healing",
  "Bag of holding",
  "Driftglobe",
]
gen.item.table.b = [
  "Potion of greater healing",
  "Potion of fire breath",
  "Potion of resistance",
  "Ammunition +1",
  "Potion of animal friendship",
  "Potion of hill giant strength",
  "Potion of growth",
  "Potion of water breathing",
  "Spell scroll (2nd level)",
  "Spell scroll (3rd level)",
  "Bag of holding",
  "Keoghtom's ointment",
  "Oil of slipperiness",
  "Dust of disappearance",
  "Dust of dryness",
  "Dust of sneezing and choking",
  "Elemental gem",
  "Philter of love",
  "Alchemy jug",
  "Cap of water breathing",
  "Cloak of the manta ray",
  "Driftglobe",
  "Goggles of night",
  "Helm of comprehending languages",
  "Immovable rod",
  "Lantern of revealing",
  "Mariner's armor",
  "Mithral armor",
  "Potion of poison",
  "Ring of swimming",
  "Robe of useful items",
  "Rope of climbing",
  "Saddle of the cavalier",
  "Wand of magic detection",
  "Wand of secrets",
]
gen.item.table.c = []
gen.item.table.d = []
gen.item.table.e = []
gen.item.table.f = []
gen.item.table.g = []
gen.item.table.h = []
gen.item.table.i = []
// gems
gen.gem = {};
gen.gem.gp10 = [
  `Azurite (opaque mottled deep blue)`,
  `Banded agate (translucent striped brown, blue, white, or red)`,
  `Blue quartz (transparent pale blue)`,
  `Eye agate (translucent circles of gray, white, brown, blue, or green)`,
  `Hematite (opaque gray-black)`,
  `Lapis lazuli (opaque light and dark blue with yellow flecks)`,
  `Malachite (opaque striated light and dark green)`,
  `Moss agate (translucent pink or yellow-white with mossy gray or green markings)`,
  `Obsidian (opaque black)`,
  `Rhodochrosite (opaque light pink)`,
  `Tiger eye (translucent brown with golden center)`,
  `Turquoise (opaque light blue-green)`
];
gen.gem.gp50 = [
  `Bloodstone (opaque dark gray with red flecks)`,
  `Carnelian (opaque orange to red-brown)`,
  `Chalcedony (opaque white)`,
  `Chrysoprase (translucent green)`,
  `Citrine (transparent pale yellow-brown)`,
  `Jasper (opaque blue, black, or brown)`,
  `Moonstone (translucent white with pale blue glow)`,
  `Onyx (opaque bands of black and white, or pure black or white)`,
  `Quartz (transparent white, smoky gray, or yellow)`,
  `Sardonyx (opaque bands of red and white)`,
  `Star rose quartz (translucent rosy stone with white star-shaped center)`,
  `Zircon (transparent pale blue-green)`
];
gen.gem.gp100 = [
  `Amber (transparent watery gold to rich gold)`,
  `Amethyst (transparent deep purple)`,
  `Chrysoberyl (transparent yellow-green to pale green)`,
  `Coral (opaque crimson)`,
  `Garnet (transparent red, brown-green, or violet)`,
  `Jade (translucent light green, deep green, or white)`,
  `Jet (opaque deep black)`,
  `Pearl (opaque lustrous white, yellow, or pink)`,
  `Spinel (transparent red, red-brown, or deep green)`,
  `Tourmaline (transparent pale green, blue, brown, or red)`
];
gen.gem.gp500 = [
  `Alexandrite (transparent dark green)`,
  `Aquamarine (transparent pale blue-green)`,
  `Black pearl (opaque pure black)`,
  `Blue spinel (transparent deep blue)`,
  `Peridot (transparent rich olive green)`,
  `Topaz (transparent golden yellow)`
];
gen.gem.gp1000 = [
	`Black opal (translucent dark green with black mottling and golden flecks)`,
	`Blue sapphire (transparent blue-white to medium blue)`,
	`Emerald (transparent deep bright green)`,
	`Fire opal (translucent fiery red)`,
	`Opal (translucent pale blue with green and golden mottling)`,
	`Star ruby (translucent ruby with white star-shapedcenter)`,
	`Star sapphire (translucent blue sapphire with whitestar-shaped center)`,
	`Yellow sapphire (transparent fiery yellow or yellow·green)`
];
gen.gem.gp5000 = [
	`Black sapphire (translucent lustrous black with glowing highlights)`,
	`Diamond (transparent blue-white, canary, pink, brown, or blue)`,
	`Jacinth (transparent fiery orange)`,
	`Ruby (transparent clear red to deep crimson)`
];
// art objects
gen.art = {};
gen.art.gp25 = [
  `Silver ewer`,
  `Carved bone statuette`,
  `Small gold bracelet`,
  `Cloth-of-gold vestments`,
  `Black velvet mask stitched with silver thread`,
  `Copper chalice with silver filigree`,
  `Pair of engraved bone dice`,
  `Small mirror set in a painted wooden frame`,
  `Embroidered silk handkerchief`,
  `Gold locked with a painted portrait inside`,
];
gen.art.gp250 = [
  `Gold ring set with bloodstones`,
  `Carved ivory statuette`,
  `Large gold bracelet`,
  `Silver necklace with gemstone pendant`,
  `Bronze crown`,
  `Silk robe with gold embroidery`,
  `Large well-made tapestry`,
  `Brass mug with jade inlay`,
  `Box of turquoise animal figurines`,
  `Gold bird cage with electrum filigree`,
];
gen.art.gp750 = [
  `Silver chalice set with moonstones`,
  `Silver-plated steel longsword with jet set in hilt`,
  `Carved harp of exotic wood with ivory inlay and zircon gems`,
  `Small gold idol`,
  `Gold dragon comb set with red garnets as eyes`,
  `Bottle stopper cork embossed with gold leaf and set with amethysts`,
  `Ceremonial electrum dagger with a black pearl in the pommel`,
  `Silver and gold brooch`,
  `Obsidian statuette with gold fittings and inlay`,
  `Painted gold war mask`,
];
gen.art.gp2500 = [
  `Fine gold chain set with a fire opal`,
  `Old masterpiece painting`,
  `Embroidered silk and velvet mantle set with numerous moonstones`,
  `Platunum bracelet set with a sapphire`,
  `Embroidered glove set with jewel chips`,
  `Jeweled anklet`,
  `Gold music box`,
  `Gold circlet set with four aquamarines`,
  `Eye patch with a mock eye set in blue sapphire and moonstone`,
  `A necklace string of pink pearls`,
];
gen.art.gp7500 = [
  `Jeweled gold crown`,
  `Jeweled platinum ring`,
  `Small gold statuette set with rubies`,
  `Gold cup set with emeralds`,
  `Gold jewelry box with platinum filigree`,
  `Painted gold child's sarcophagus`,
  `Jade game board with solid gold playing pieces`,
  `Bejeweled ivory drinking horn with gold filigree`,
];
